In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# checking the version of pytorch framework
torch.__version__

'2.4.1+cu121'

In [5]:
scaler = torch.tensor(0)

In [9]:
scaler.shape

torch.Size([])

In [4]:
!invidia-smi


/bin/bash: line 1: invidia-smi: command not found


In [14]:
# this is how to initialize random tensors in pytorch
randomTensor = torch.rand(10,2)
randomTensor

tensor([[0.9314, 0.3665],
        [0.9548, 0.2110],
        [0.7480, 0.4766],
        [0.5774, 0.2573],
        [0.7066, 0.6425],
        [0.5275, 0.6550],
        [0.5024, 0.0378],
        [0.4103, 0.5895],
        [0.4939, 0.5485],
        [0.3585, 0.4335]])

In [13]:
# initializing random tensors in pytorch
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2606, 0.4033, 0.1764, 0.4416],
        [0.6566, 0.6088, 0.1918, 0.4231],
        [0.8508, 0.6781, 0.6780, 0.9786]])

In [ ]:
# creating zeros tensors in pytorch
zeros = torch.zeros(3,4)

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.zeros_like(sclaer)

tensor(0)

In [ ]:
range = torch.arange(start=0,end=10,step=2)

In [ ]:
range

tensor([0, 2, 4, 6, 8])

In [ ]:
np.abs(torch.tensor([1,-2,3]))

tensor([1, 2, 3])

In [ ]:
tens = torch.tensor(data=[1,2,3,4],
             device="cpu",
             requires_grad=False)

In [ ]:
tens.argmax()

tensor(3)

In [ ]:
tens


tensor([1, 2, 3, 4])

In [ ]:
tens.argmin()

tensor(0)

In [ ]:
tens.shape

torch.Size([4])

In [ ]:
# reshaping tens
tens.reshape(4,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
# how to use permute function in pytorch
tense = torch.randn(3,4,5)

In [ ]:
tense.shape

torch.Size([3, 4, 5])

In [ ]:
new = torch.permute(tense, (2,1,0))

torch.Size([5, 4, 3])

In [ ]:
# how to set to set device agnostic code

if torch.cuda.is_available():
  device = "cuda"
  print("cuda is available")
else:
  device = "cpu"
  print("cuda is not available")

cuda is not available


In [ ]:
name = torch.tensor([2,3,4,5])

In [ ]:
name.numpy()

array([2, 3, 4, 5])

In [ ]:
num = np.array([2,3,4,5,6])

In [ ]:
one = torch.rand(0,10)
two = torch.rand(0,10)


In [ ]:
import torch as torch

In [ ]:
device = torch.backends.mps.is_available()

In [ ]:
print(f"this is apples gpu {device}")

this is apples gpu False


In [ ]:
import torch
from torch import nn
from torch.nn import functional as f
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
%matplotlib inline


In [ ]:
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
df = pd.read_csv(url)

In [ ]:
class Model(nn.Module):
  def __init__(self,in_features=4,\
               hidden_layer_1=8, hidden_layer_2=12,\
               out_features=3):
    super().__init__()
    self.linear1 = nn.Linear(in_features,hidden_layer_1)
    self.linear_2 = nn.Linear(hidden_layer_1,hidden_layer_2)
    self.linear_3 = nn.Linear(hidden_layer_2,out_features)
  def forward(self,x):
    x = f.relu(self.linear1(x))
    x = f.relu(self.linear_2(x))
    x = f.softmax(self.linear_3(x))
    return x


In [ ]:
random_seed = 42
torch.manual_seed(random_seed)
model = Model()

In [ ]:
model

Model(
  (linear1): Linear(in_features=4, out_features=8, bias=True)
  (linear_2): Linear(in_features=8, out_features=12, bias=True)
  (linear_3): Linear(in_features=12, out_features=3, bias=True)
)

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
X = df.drop("species",axis=1)
y = df["species"]

In [ ]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
      dtype=float32)

In [ ]:
# encoding the target class
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
y = y.astype("float32")

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,\
                train_size=0.8,test_size=0.2,shuffle=True,\
                  random_state=41)

In [ ]:
X_train

sepal_length  sepal_width  petal_length  petal_width
79            5.7          2.6           3.5          1.0
54            6.5          2.8           4.6          1.5
106           4.9          2.5           4.5          1.7
90            5.5          2.6           4.4          1.2
145           6.7          3.0           5.2          2.3
..            ...          ...           ...          ...
26            5.0          3.4           1.6          0.4
89            5.5          2.5           4.0          1.3
65            6.7          3.1           4.4          1.4
80            5.5          2.4           3.8          1.1
140           6.7          3.1           5.6          2.4

[120 rows x 4 columns]

In [ ]:
X_test

sepal_length  sepal_width  petal_length  petal_width
119           6.0          2.2           5.0          1.5
128           6.4          2.8           5.6          2.1
135           7.7          3.0           6.1          2.3
91            6.1          3.0           4.6          1.4
112           6.8          3.0           5.5          2.1
71            6.1          2.8           4.0          1.3
123           6.3          2.7           4.9          1.8
85            6.0          3.4           4.5          1.6
147           6.5          3.0           5.2          2.0
143           6.8          3.2           5.9          2.3
127           6.1          3.0           4.9          1.8
39            5.1          3.4           1.5          0.2
38            4.4          3.0           1.3          0.2
93            5.0          2.3           3.3          1.0
23            5.1          3.3           1.7          0.5
133           6.3          2.8           5.1          1.5
30            4.8          3.1           1.6          0.2
83            6.0          2.7           5.1          1.6
37            4.9          3.1           1.5          0.1
41            4.5          2.3           1.3          0.3
81            5.5          2.4           3.7          1.0
120           6.9          3.2           5.7          2.3
43            5.0          3.5           1.6          0.6
2             4.7          3.2           1.3          0.2
64            5.6          2.9           3.6          1.3
62            6.0          2.2           4.0          1.0
56            6.3          3.3           4.7          1.6
67            5.8          2.7           4.1          1.0
49            5.0          3.3           1.4          0.2
63            6.1          2.9           4.7          1.4

In [ ]:
# training our model to make a prediction the type of flower
Epoch = 100
loss_list = []
for epoch in range(Epoch):
  y_predict = model.forward(X_train)
  loss = measure(y_predict,y_train)
  loss_list.append(loss)
  if epoch % 10 == 0:
    print(f"epoch {epoch} and loss {loss}")
  # doing back propagation in pytorch


  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float